---
- name: Create monitoring directory
  file:
    path: "{{ monitoring_stack_dir }}"
    state: directory

- name: Get Tailscale IP address
  ansible.builtin.shell: "docker exec tailscale tailscale ip -4"
  register: ts_ip_output
  changed_when: false

- name: Set Tailscale IP fact
  ansible.builtin.set_fact:
    ts_ip: "{{ ts_ip_output.stdout | trim }}"

- name: Copy Grafana configuration (static)
  ansible.builtin.copy:
    src: grafana/
    dest: "{{ monitoring_stack_dir }}/grafana/"
    mode: '0644'
    directory_mode: '0755'

- name: Copy Prometheus configuration (static)
  ansible.builtin.copy:
    src: prometheus/
    dest: "{{ monitoring_stack_dir }}/prometheus/"
    mode: '0644'
    directory_mode: '0755'

- name: Copy Blackbox Exporter configuration (static)
  ansible.builtin.copy:
    src: blackbox/
    dest: "{{ monitoring_stack_dir }}/blackbox/"
    mode: '0644'
    directory_mode: '0755'

- name: Render Docker Compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ monitoring_stack_dir }}/docker-compose.yml"
  vars:
    gf_security_admin_user: "{{ monitoring_secrets.grafana.gf_security_admin_user }}"
    gf_security_admin_password: "{{ monitoring_secrets.grafana.gf_security_admin_password }}"
    tailscale_ip: "{{ ts_ip }}"

- name: Deploy and Start Services
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_stack_dir }}"
    state: present