backups:
    restic_password: ENC[AES256_GCM,data:kPchgRHQx7155Msz0pRySXvQY/gER1VEdJaAxiRkkyOolmnsv+Px1fUtpDu9bL+dKeCNjRNVp2LxAsLWBeGWXQ==,iv:DHz4m7xZv8aSf72y13BjH12vLvnppMBMpRqc0mOpUHc=,tag:lqtctf3vRJeAnEOpSJ0xIg==,type:str]
    b2_key_id: ENC[AES256_GCM,data:qkz+bMOUCUYrgNkIpdPk1h5Tt/NJgMUSzw==,iv:b+/LbQmKfqvzAAunXPI3HD3XkYGQ/tvgvzhRBJAOx5A=,tag:6cCGXHAL42zry2KmJCK00Q==,type:str]
    b2_key_secret: ENC[AES256_GCM,data:LwRkV3Zw+8vkOdfMqlTGOKzFm3E3G2j6gtNVbK3jqQ==,iv:j3lUljrNEfN68wcleuNlPGqYqchaLw6kYP+Zfrxyb70=,tag:H/RoW8fmTEo7VLH0bws6MA==,type:str]
    b2_bucket_name: ENC[AES256_GCM,data:6R7i/EcCni6Q3JI8TyHaYVIR,iv:/FdPpgaTz+48z8CiHccf4S416jsN9nmg4txGY+U/qqk=,tag:hjWC+f25AeXvvkvInpVnQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxrnm8u2p0n8yg9xfml0p9j79phe954ju0w5l6keer2k8ulurgtqtxmjy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeEZpeDROYzVRSy9CTTJC
            Y0J4L0p1UFVrbXhYei9PbmorNkIzT2xXQUYwClBpUFFCYm55YzJHcjRDZUZablJY
            eUxSRWk2WFpFeGllN0IwTzlSeFFwM0UKLS0tIEhKV0dSeHZOV2VyK1cxSThPYVBU
            czYrTlJUalJ2S3RXTzBzckdOYS9CczgK7NOBU6RrJt413hwGnVb8iOJhc0ndUDnl
            fmQCjSeVp/TLMNNuzyKJazDLVkiAEZycGoho3tbjVP2aIwC5aUzRCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T12:02:52Z"
    mac: ENC[AES256_GCM,data:kxFukVcJmKOP6aMjgHd4MAASipeiU/sZR3Uj9fWDXwMsV21NsHCKDps4MyX+IJHsPlbdzw8HYr41YOOyHY3Zda3ERP/gsQHmrD5GhNTUvStZ1/1yBpBcwT01GhpRx0xlCTHWVps3eUPnCaA4H0U3aFfv1vd4RIWTB6sY1bA4OtE=,iv:Ttpm/MJb+SB9ugOM/zmSK+PSXUxbVVDBbo3KapS+xwQ=,tag:WeUfSDhuVGTPhll19vRZUA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
