database:
    db_password: ENC[AES256_GCM,data:y668UYIAoiBE6eYyD44qhQ+bzdLRn5vV,iv:tJ0EIGYtJjs9SOhRIWE7o8EHXbTVRVAnToU2UqABW+A=,tag:ahCpoYFPs9DgSl3RazRAQg==,type:str]
    db_usename: ENC[AES256_GCM,data:a+pUa1Rs,iv:iDqIqZ9nftkPVescpUaLKblRETTBD7HDE/Gby8LqZpw=,tag:ZeSOTdqZ8Zcgqd+M+5Cekw==,type:str]
    db_database_name: ENC[AES256_GCM,data:c/POAzyB,iv:OEmEgka/SNe9sjLGyMNXi/FQ93mWBjJM9ob33rcxq/8=,tag:1US4+1RTp2o++BwJicwvHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxrnm8u2p0n8yg9xfml0p9j79phe954ju0w5l6keer2k8ulurgtqtxmjy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeFdLTHN1TXVpcm1hNTZh
            cmtaTDBTdTNRK0FrU1RjZVdYb0s5YkpGcUhjCi9wVGh3TlJ6QmYvc3NlalFVdWZh
            cjh2NFYzMTh5bTYrbHhhK3llVWhBRnMKLS0tIHVTT1A2UG1wNnZyVklBdlUxZlRC
            QUJBQW8va0p2UWpaajE1WVp0NWFvWlkKfGt5WmIXerzvoamjv9/ajsQCcejpWxxv
            NeDVOarcoxuIaN5t2jZIYcGZcq6XpTz/z0vnsnFfY/fYL0XDHOBzKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T16:44:05Z"
    mac: ENC[AES256_GCM,data:izEODFgMes7sfGcTeehojxaGLLY1k288O/0G+UMTz/hehTE6PglozYGLTxU6APRrNx0PeOjObS725jZc349mkqksw3bg0cGWR3vhobz3/hrdLexNPYVA1ZQRXSuazgFF7TZtnmO+v2qwqPvdjljcHh3Io+nfzPKWstqVAzVDczI=,iv:87wiEBC9m5FoXw3Mw0ITOmio5hM8b5zlkBYflhGKUvU=,tag:gwC+bUrtpl588TUNxNDe5Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
