grafana:
    gf_security_admin_user: ENC[AES256_GCM,data:RBdcehs=,iv:EOEPGMCfbkLeHHD0a4BxgrAimVyxvRn8aP7LdrxciA0=,tag:m9YgUsO66Uzx1wbV4Ym+Jw==,type:str]
    gf_security_admin_password: ENC[AES256_GCM,data:80dKLTtPlt3ug03JJv48Hjf7i2P/dVgL,iv:pnEN6tSRSfSU4RDhVrX4Ta0a2S6viN90cZ2Q9ktNp2I=,tag:8PjJpeT6nSir8NZVFvf5Tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxrnm8u2p0n8yg9xfml0p9j79phe954ju0w5l6keer2k8ulurgtqtxmjy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaL080bGp1S0IzNkVXQkhZ
            S3cwZXQ3dmh2YkdBWFNieVFxVHhVZlpEUGhBClhmcE1jeG9KbEtTQVNmM25BS3lR
            WUF5U3FVc3FJLzdZSTE3blk4S2dyejAKLS0tIE5RaUZiWC8zaGcxTlp2dlJmUmU3
            RldjenJ5cFlpb3BCcDJPS2JtdTk1RjgKbh29ESWxLOTh2n3mLh7D9/hoG83A9iu+
            NptPAnfmzbkjK+9+vRHU0i97cSBMDr2JeBWUKCJObu5k6BktydWueQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T17:43:25Z"
    mac: ENC[AES256_GCM,data:e53fav9kcBOAy6MRC+hJckKmguz+we6n2WaB2al+tonjgzlJVTH04uHQmRa5dq40lzHP2s+E5B8gRLCPubPDHLtpZPGuP0HOWsrEvwG7gLWYHph8sCWK7+1+oaTlNteRLxNjnn0guikHu7v8rqy+15lFyM4SXlKAop8PnTCivWo=,iv:p5nJpdj9zkLSj8JUR6sNZxM0mTJ7W2zYdcdiEr8pIL0=,tag:Q50cPY9p1Uaih4R7sIaa1A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
