tailscale:
    auth_key: ENC[AES256_GCM,data:qyjSMgj3RjUztjtJoAAJVtI6qh19xuDTC2PsqlMQrmGLXiz4ypFDxVYoDPVjZ+kONYgkKHaJoc6/vpXUKhA=,iv:RzH1qsxliHmuMTOZSSDc1pM/iJpSuAXzGFw5FlPRNW0=,tag:TIWpf6juY4zlnHoIHTGkaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxrnm8u2p0n8yg9xfml0p9j79phe954ju0w5l6keer2k8ulurgtqtxmjy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcEZnM0h6OFd2OFZIWmht
            QzQ0WW4wMkpqVG1NQnVYYm5Vd2hKU3BZcFhFCnBkdG5UTXVVTVFkMUl4eHZrc1ZW
            WlUxUE12OWFqRjNyTWsrbVpqQUpJRm8KLS0tIEdONGtZaTFWS1FoVUdtNFpmRVZ1
            TVdQL1JjSFRwKzFjQ1lGbUJZdGlUM3cKxNGfZsXaynnU0IJemIt4cbtIke4xtNuA
            l3QgTnF5zxj2d9afFWSLBluheZQPojy7tBdcYw6gspHfDtIX8QYVKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T11:08:08Z"
    mac: ENC[AES256_GCM,data:wNiYFA/IbqROLNuE9qWYhXs4VxfNG5x6pPcrUcrddYkQZwClKaf2F9hUbEjfRd8Ip28ai8Iy6aCnUOH0Oit6hL7BAuBCcaWMnU0Ex9fN5T7IAwS6tghKPXiWXC2wUPi2DtLoq2qysuR/wJWfh87lx06kv1NpajONhbZcl3ItEKU=,iv:Ju/Y24yPThvdgBAoECg93nk+peUzLNvjBqoubdT58tc=,tag:rVzmLWXVrTNHYn7XfTqegQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
