wireguard_server:
    server_private_key: ENC[AES256_GCM,data:09ipoBImgCTktZlN9OfbSbMBlP/0blczJIwuYkiFiN7UW9pKuSQLgj8K1pM=,iv:fqf6KafGcx9osevSHAcglSGNTAI+XXpBt/m5betsp4M=,tag:pokuc+vMD+Oz3p6bmvT2Ww==,type:str]
    server_public_key: ENC[AES256_GCM,data:8xOrs/TfYvCW25bp8HX1O1PWs0eg7gJbdpLh8XPR+tBrcmEy+Hvk6KUMB3s=,iv:nj2XuB4/EoomoqUtLvx3gj21+bJXt5jy2lj9IGgr4EU=,tag:fME1CcMXqt0luqNwWfYUew==,type:str]
wireguard_clients:
    phone:
        private_key: ENC[AES256_GCM,data:LOsZpaGHsutNfHj56bGe9HwPeI5XDtsQ+7Ame8KTR91LdcOHLnqA2Coo8uA=,iv:FxtygqjoxG/0ZpqiENK9XqWxgVm/AZk/rzTNw8+szB8=,tag:YVfFvZ2/6irJpALJkPT5hg==,type:str]
        public_key: ENC[AES256_GCM,data:L53BjM4ldiR/1t8bub5ESKDYF9hAJUr3MMO3TQ9jwZstX2jl05ZXoy10NW8=,iv:eiT25LgJlnGVsOeFczODSJFBuanvY1ZGexrU7KysnIg=,tag:fag8u5vBzgLCNAy+FNQQRQ==,type:str]
    raspberry:
        private_key: ENC[AES256_GCM,data:yp9LhrsHHmkyK7UELlOmJ7rZ1iLferwYjVBNQC5Tb2OLwXrcYNho8wPjBnI=,iv:mK1ykc0GF1RScX6LRSk07Zp+rAn2Z6UqzP0lFYyNm+0=,tag:hdUwNK+Te2Qvv3K0LHH31w==,type:str]
        public_key: ENC[AES256_GCM,data:3mTUIQtrOY6YO3l9qpBuJxCwjgfq8C0K/9gT4qELc6YaAVzTG1cFzoI6gF8=,iv:gd1M2zegI7IhoIYBmcZKB/GY6KP+QPUBf5K9Hb2or/k=,tag:7TuBSXANfJ8C1/ocE2nEDg==,type:str]
    windows:
        private_key: ENC[AES256_GCM,data:9yO67R9yPLPPG3eZ3DX7OqaHTueU6plUell53tLBmz39rTtLc4GS+OH4cPY=,iv:XHlhr7+n+4IYaPHbyKt/+VsRdzpA23UnikAo2cfu9rs=,tag:xwI7cL1/E/WeOiyjdc/yqg==,type:str]
        public_key: ENC[AES256_GCM,data:VQBYNUQ51AyDy8bQAmu73x1XcD1RZCd6/6zOThU20iWgwDQFLvFX9/8cdrU=,iv:EGntL84oLK0jKCd7Y12G2nZCPsUtQpXwb7qlrYjdaDM=,tag:LAArWdx1c21vPhgmVXqmcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxrnm8u2p0n8yg9xfml0p9j79phe954ju0w5l6keer2k8ulurgtqtxmjy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjME9Qdmt1bE5ZSU1OeWtZ
            Unc0MWVjaUtwblJ0L2hsN1JCUVgzdk4xcnowClJHTEdNOEl4QjYxRzY5V0FCYWdu
            bkZLTzkwTFVBOXZYamVmQUFlVE1RdlEKLS0tIFRLME4xbzY3R0VrU1Y1U0lLbjZm
            STdML2xyeEZoSG11MCtKY2NUaDRramcK3e7kOn70Edst5LukAiHNNqV8IQQ0UPcA
            IMsHpmr2GK0/OLDVngZ5/Sh/fhXs0Sjf23iStXYEX0pXPIZfqL4L3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T18:09:38Z"
    mac: ENC[AES256_GCM,data:jlUMojqbFLD/eQ4ylHyJmz4wCqkQe+iFB6D/tH+OcPW85dcn4nedgJA3aG5goG8rp3qUsE6gSMfcvHI3zeWoK8Vi8N8bHLaa7QOSTFgNOlcIGERVmwJwCgxH78dZ7NPLzZqmf1sxsuTf+i7hn1FjXyUhdXh+vI/YcNwkEqRmrsc=,iv:jCGjcfyW3KWzkoprjk7Ka1EhL5MA6WfFqEg2jMXJAvM=,tag:unyAxTPOkbvrEwTnayhNFw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
