---
- name: Install restic
  apt:
    name: restic
    state: present

- name: Create backup script from template
  template:
    src: run-restic-backup.sh.j2
    dest: /usr/local/bin/run-restic-backup.sh
    mode: '0700'
    owner: root

- name: Create systemd service file
  template:
    src: restic-backup.service.j2
    dest: /etc/systemd/system/restic-backup.service

- name: Create systemd timer file
  template:
    src: restic-backup.timer.j2
    dest: /etc/systemd/system/restic-backup.timer

- name: Enable and start restic backup timer
  systemd:
    name: restic-backup.timer
    enabled: yes
    state: started
    daemon_reload: yes
