---
- import_playbook: stage_ssh_key.yml

- name: Configure Offsite Backups for Immich
  hosts: raspberry
  become: yes
  vars:
    backup_secrets: "{{ lookup('community.sops.sops', '../secrets/backup_secrets.yaml') | from_yaml }}"
  roles:
    - backup
