---
- hosts: vpn_server
  become: yes
  tasks:
    - name: Enable IPv4 forwarding in sysctl
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes
        
    - name: Create server configuration
      template:
        src: ../templates/server.conf.j2
        dest: /etc/wireguard/wg0.conf
      vars:
        server_tunnel_ip: "{{ vpn_server_internal_ip }}"
        server_port: "{{ vpn_server_port }}"
      notify: Restart WireGuard

  handlers:
    - name: Restart WireGuard
      systemd:
        name: wg-quick@wg0
        state: restarted
        enabled: yes