---
- import_playbook: stage_ssh_key.yml

- name: Setup Monitoring Stack
  hosts: raspberry
  vars:
    # Decrypt secrets on the fly
    secrets: "{{ lookup('community.sops.sops', '../secrets/main.yaml') | from_yaml }}"
  roles:
    - monitoring
