---
- import_playbook: stage_ssh_key.yml

- name: Setup Monitoring Stack
  hosts: raspberry
  vars:
    # Decrypt secrets on the fly
    monitoring_secrets: "{{ lookup('community.sops.sops', '../secrets/monitoring_secrets.yaml') | from_yaml }}"
  roles:
    - monitoring
