---
- hosts: vpn_client
  become: yes
  tasks:
    - name: Enable IPv4 forwarding in sysctl
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Fetch Pi public key to Laptop
      fetch:
        src: /etc/wireguard/public.key
        dest: "{{ playbook_dir }}/../client_profiles/raspberry_client/public.key"
        flat: yes

    - name: Setup Pi wg0.conf
      template:
        src: ../templates/linux_client.conf.j2
        dest: /etc/wireguard/wg0.conf
      vars:
        client_tunnel_ip: "{{ (vpn_clients | selectattr('name', 'equalto', 'raspberry_client') | first ).ip }}/24"
        server_public_key: "{{ hostvars['ec2_server']['wg_public_key_raw']['stdout'] }}"
        server_endpoint: "{{ hostvars['ec2_server']['ansible_host'] }}"
      notify: Restart WireGuard Client

  handlers:
    - name: Restart WireGuard Client
      systemd:
        name: wg-quick@wg0
        state: restarted
        enabled: yes