---
- hosts: vpn_server
  tasks:
    - name: Create Client Configs
      delegate_to: localhost
      template:
        src: "{{ playbook_dir }}/../templates/client.conf.j2"
        dest: "{{ playbook_dir }}/../client_profiles/{{ item.name }}/{{ item.name }}.conf"
      loop: "{{ vpn_clients }}"
      vars:
        client_private_key: "{{ lookup('file', playbook_dir + '/../client_profiles/' + item.name + '/private.key') }}"
        client_tunnel_ip: "{{ item.ip }}/32"
        client_dns: "1.1.1.1, 8.8.8.8"
        server_public_key: "{{ wg_public_key_raw.stdout }}"
        server_endpoint: "{{ ansible_host }}"

    - name: Generate QR Code for Phone Configuration
      delegate_to: localhost
      shell: |
        python3 -c "import qrcode; qrcode.make(open(r'{{ playbook_dir }}/../client_profiles/{{ item.name }}/{{ item.name }}.conf', 'r', encoding='utf-8').read()).save(r'{{ playbook_dir }}/../client_profiles/{{ item.name }}/{{ item.name }}.png')"
      loop: "{{ vpn_clients }}"
      when: item.type == "phone"