- name: Teardown Wireguard on Raspberry Pi
  hosts: vpn_client
  become: true
  tasks:
    - name: Stop and disable WireGuard service
      systemd:
        name: wg-quick@wg0
        state: stopped
        enabled: false
      ignore_errors: true