---
# 1. Generate client WireGuard profiles (runs locally on the Ansible control node)
- import_playbook: playbooks/generate_profiles.yml

# 1. Infrastructure Layer
- import_playbook: playbooks/wg_server.yml

# 2. Application Layer
- import_playbook: playbooks/immich.yml
- import_playbook: playbooks/monitoring.yml

# 100. Client Layer (Local Config Generation)
- import_playbook: playbooks/setup_clients.yml
